name: bloc_generic_streams
description: A Flutter package to implement Didier Boelens's BlocProvider and simplified use of Stream using Dart's Generics.
version: 1.4.0
homepage: https://github.com/fmmalta/bloc_provider_generic_streams

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  rxdart: ^0.25.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
